---
title: "LDA-QDA Analysis"
author: "Pooja Khatri"
date: "4/28/2023"
output: html_document
---



```{r}
library(data.table)
library(caret)
library(MASS)
library(DescTools)

trn_url = "https://raw.githubusercontent.com/anecnhoj53/stat432/master/loan_balanced_trn.csv"

tst_url = "https://raw.githubusercontent.com/anecnhoj53/stat432/master/loan_balanced_tst.csv"

trn <- read.csv(url(trn_url))
tst <- read.csv(url(tst_url))
```



```{r, eval = FALSE}

trn_lda = lda(TARGET ~ DAYS_EMPLOYED + REGION_RATING_CLIENT_W_CITY + OCCUPATION_TYPE + DAYS_BIRTH + NAME_CONTRACT_TYPE + DAYS_LAST_PHONE_CHANGE + DEF_30_CNT_SOCIAL_CIRCLE + AMT_GOODS_PRICE + AMT_CREDIT + REG_CITY_NOT_WORK_CITY + AMT_INCOME_TOTAL + FLAG_OWN_CAR + REGION_POPULATION_RELATIVE + CODE_GENDER, data = trn)

pred.lda.trn = predict(trn_lda, trn)

pred.lda.tst = predict(trn_lda, tst)

table(pred.lda.tst$class, tst$TARGET)
mean(pred.lda.tst$class != tst$TARGET)


```


```{r, eval = FALSE}

trn_lda = lda(TARGET ~ DAYS_EMPLOYED + OCCUPATION_TYPE + DAYS_BIRTH + DAYS_LAST_PHONE_CHANGE + DEF_30_CNT_SOCIAL_CIRCLE + AMT_GOODS_PRICE + AMT_CREDIT + REG_CITY_NOT_WORK_CITY + AMT_INCOME_TOTAL + FLAG_OWN_CAR + REGION_POPULATION_RELATIVE + CODE_GENDER, data = trn)

pred.lda.trn = predict(trn_lda, trn)

pred.lda.tst = predict(trn_lda, tst)

table(pred.lda.tst$class, tst$TARGET)
mean(pred.lda.tst$class != tst$TARGET)

```



```{r, eval = FALSE}

trn_qda = qda(TARGET ~ DAYS_EMPLOYED + REGION_RATING_CLIENT_W_CITY + OCCUPATION_TYPE + DAYS_BIRTH + NAME_CONTRACT_TYPE + DAYS_LAST_PHONE_CHANGE + DEF_30_CNT_SOCIAL_CIRCLE + AMT_GOODS_PRICE + AMT_CREDIT + REG_CITY_NOT_WORK_CITY + AMT_INCOME_TOTAL + FLAG_OWN_CAR + REGION_POPULATION_RELATIVE + CODE_GENDER, data = trn)

pred.qda.trn = predict(trn_qda, trn)

pred.qda.tst = predict(trn_qda, tst)

table(pred.qda.tst$class, tst$TARGET)
mean(pred.qda.tst$class != tst$TARGET)

```



```{r, eval = FALSE}

trn_qda = qda(TARGET ~ DAYS_EMPLOYED + REGION_RATING_CLIENT_W_CITY + OCCUPATION_TYPE + DAYS_BIRTH + NAME_CONTRACT_TYPE + DAYS_LAST_PHONE_CHANGE + AMT_GOODS_PRICE + AMT_CREDIT + REG_CITY_NOT_WORK_CITY + AMT_INCOME_TOTAL + FLAG_OWN_CAR + REGION_POPULATION_RELATIVE + CODE_GENDER, data = trn)

pred.qda.trn = predict(trn_qda, trn)

pred.qda.tst = predict(trn_qda, tst)

table(pred.qda.tst$class, tst$TARGET)
mean(pred.qda.tst$class != tst$TARGET)

```



```{r, eval = FALSE}

library(klaR)
modelstepL <- stepclass(TARGET ~ ., "lda", direction = "both", data = trn)

```












